### PR TITLE
Gem update & Cleanup

### PR DESCRIPTION
**Pull request by malachaifrazier**
Updated rspec gem, created a `.rspec` file & cleaned up some comments.

### CODE REVIEW

**Comment by MGerrior** [comment]
Do we need to bump the gem version [here](https://github.com/MGerrior/shoulda-whenever/blob/master/lib/shoulda/whenever/version.rb#L3) since we updated code in the module?

**Comment by malachaifrazier** [comment]
Excellent point. Yes, my gut tells me you're correct. 
@MGerrior should it go to '0.0.2', then?

**Comment by MGerrior** [comment]
Yea, minor bump seems fine since there is nothing here that should have any sort of impact on the user. `0.0.2` it is! Thanks, good to know others are actually using this!

**Comment by malachaifrazier** [comment]
Version bumped to `0.0.2`
Thanks for building this!

**Comment by MGerrior** [comment]
No problem, hopefully it helps others from trying to schedule a rake task every `:firday` like I did... I'll merge this in and then I think I need to publish the new version to rubygems.org. And thank you for helping to keep it up to date!

**Pull request merged**
